### ISSUE TITLE
[Feature] Pages

### ISSUE THREAD

**Issue by MathiewMay** [Starz0r/AreWeAntiCheatYet#112]
There should be pages, with maybe 10 items per page. it would make it allot easier to navigate instead of just scrolling down.

**Comment by Curve** [comment]
The page is built to support browsers that have Javascript disabled, adding pagination would Render the support useless since they wouldn't be able to navigate the list

Also imho it's way better to just scroll down instead of having to click a next page button the whole time, that would just be annoying
