### ISSUE TITLE
Back 4 Blood

### ISSUE THREAD

**Issue by Mar0xy** [Starz0r/AreWeAntiCheatYet#142]
### Game Title

Back 4 Blood

### Game Website

https://www.back4blood.com

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

🎉 Confirmed

### Proof of Mention

https://www.reddit.com/r/Back4Blood/comments/puc9le/developers_have_the_option_to_support_linux_with/he30d87/

**Comment by doogie544** [comment]
It seems pretty clear to me from that post that they're considering it but that it's still in the category of unconfirmed. 

I will admit it does look promising. However, I read that statement more to be we are deciding if it's feasible and that if it is we are going to enable it rather than a hard confirmed. Imo it's a bit too early from that statement to market as confirmed and then to be wrong, it is much better to leave it as is until there's a more definite statement from the developers. It would disappoint people a lot more to think it's confirmed and then find out later that it was incorrect
