### ISSUE TITLE
Rust

### ISSUE THREAD

**Issue by screenslaver4443** [Starz0r/AreWeAntiCheatYet#170]
### Game Title

Rust

### Game Website

https://rust.facepunch.com/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

🎉 Confirmed

### Proof of Mention

https://www.gamingonlinux.com/2021/07/garry-newman-of-facepunch-mentions-working-with-eac-for-rust-on-linux-with-proton

**Comment by alex9099** [comment]
Rust last i tried (maybe an year ago) could be played on servers with EAC disabled, while this gives a huge handicap on which servers can be played, there's a few which can be used (for example deadlock's)
@Starz0r (not sure if i should open a new issue on this one since it's not really an "update")
