### ISSUE TITLE
Warframe

### ISSUE THREAD

**Issue by ghost** [Starz0r/AreWeAntiCheatYet#232]
### Game Title

Warframe

### Game Website

https://www.warframe.com/

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

https://www.protondb.com/app/230410

**Comment by doogie544** [comment]
Are you even sure Warframe has and anticheat?  

Just because a game shows as working on protondb that does *not*  make protondb a good source to cite as proof.
None of those reports on the page mention anticheat.

I think this report may be outside of the scope of this project.  I could be wrong but I have not been able to find any mention of Warframe having anticheat.

**Comment by PedroSilva8** [comment]
Warframe does have anti-cheat but from what I search it does simple stuff like detecting if CheatEngine is running, personally I don't believe is worth it putting on the page
