### ISSUE TITLE
Sort the Games in alphabetical order.

### ISSUE THREAD

**Issue by SamPingu** [Starz0r/AreWeAntiCheatYet#233]
Can we have the games in the site sorted by alphabetical order or by platform (i.e., WINE/Proton & Linux Native) and then sort them alphabetically under the platform group?

**Comment by Starz0r** [comment]
The current sorting order of the games is actually very intentional and strategic. By putting very popular games at the top, it's almost guaranteed they will be looked at first, applying pressure on these studios to add support.

I'm open to having other sorting options that are non-default. If anyone would like to open a PR for that, feel free.

**Comment by SamPingu** [comment]
Wow! Thank you allowing various sorting methods and for the new look for the Web Site. It looks absolutely gorgeous and is very easily readable.
