### ISSUE TITLE
Update Smite

### ISSUE THREAD

**Issue by Kylianalex** [Starz0r/AreWeAntiCheatYet#349]
### Game Title

Smite

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

https://www.gamingonlinux.com/2022/01/top-100-steam-games-running-on-linux-january-2022-edition/

**Comment by doogie544** [comment]
The source for that list is protondb which has had erroneous reports about proton Smite working.

I just checked just now and I can tell you that EAC is not working.  The logs still look identical to here

https://github.com/Starz0r/AreWeAntiCheatYet/issues/340

In fact the game does not even launch in GE 7.2 nor any of valves protons.  It will give you an EAC error that shows it is looking for the Windows version of EAC in GE 7.2 and Valve's proton 7

The site protondb is a good site but a bad source for knowing if proton compatible EAC is working.  That is particularly true with Smite (and likely Paladins)  as the game has a history of working for a short time after updates while EAC is not fully enabled.

The only way you will know if a game with EAC is really working is if you look at the logs.  There is also almost certainly also going to be an announcement from the devs as well that support has been enabled.  

Moreover the article does not mention that EAC in Smite is actually working only that protondb says it is working and if you look at the protondb site for smite it shows that the rating is trending down and most of the recent reports show it as borked

**Comment by bernharl** [comment]
Smite works with the latest proton-GE and the EAC runtime installed on Steam

**Comment by doogie544** [comment]
Here's the problem, the only way it works is by creating system links to EAC BAC files from one directory to another. 

If you have to start modifying EAC folders with system links I'm not sure that you can consider that officially supported. 

What the script for smite does with GE you could actually probably do yourself and have it work in fact reportedly it's working with proton experimental as well. It creates system link between 

`...../steamapps/Smite/easy anti cheat/(so files for 32 &64 bit)`

And

`..../Smite/binaries/(Win64 or 32 respectively)/easyanticheat`

If they don't have the files in the correct place be at intentionally or accidentally I don't think you can say it's officially supported. Any work around that requires system linking or otherwise messing with EAC files is a bit dubious even if it seems to work. 

I've been searching off and on for a couple of days and I'm unable to find any official word from hi-rez that they have enabled it, in fact I have been able to find no word from them at all with the exception of the statement they gave the verge. 

I think it's a moot point anyway because if I'm not mistaken it's now marked as supported on the website anyway
