### ISSUE TITLE
Squad is not officially supported.

### ISSUE THREAD

**Issue by electronybble** [Starz0r/AreWeAntiCheatYet#465]
Nowhere on joinsquad.com is there any official mention of Linux support.

**Comment by pbogut** [comment]
If it works then its supported I guess. Apex Legends also never mentioned that they support Linux and it works and is steam verified. It was even broken for few hours as they removed support by mistake, and then put it back after issue reports. Never officially mentioned it anywhere as far as I'm aware. 

If company officially says they support Linux, then they have to support Linux. They don't say anything so if any issues occur they can say they don't support Linux and you can go cry to Valve.

**Comment by electronybble** [comment]
What you describe is the 'runs' category. Squad belongs in the runs category, not the supported category.

**Comment by pbogut** [comment]
With that logic Apex Legends also belongs to "Running" category and probably more. 
Is there an explanation what each category is for?  I thought running was for things that requires workarounds or are using anti-cheats that not support Linux officially. 
EAC and Battleye won't work unless they are set up by developer to work on Linux, other anti-cheats may work now but then be updated and stop working on Linux.

**Comment by Curve** [comment]
Apex is in the supported category because the devs went out of their way to enable EAC support for Linux, Squad is kind of the same story, updates broke EAC support and it was fixed 

This implies to me that the devs are trying to support Linux even though they haven't mentioned it explicitly you can see them trying to

Running is meant for games that require workarounds or where reports of bans or such have been made - They run but seemingly not because the devs intend to support Linux.
A good example for this is Genshin, while it works it requires heavy workarounds and the devs don't seem to be actually interested in supporting Linux

**Comment by Curve** [comment]
I will add a more indepth explanation as to which state means what soon

**Comment by electronybble** [comment]
Maybe drop the word 'official' from the supported category? If the publisher/devs do not make any mention of Linux support, then it is unofficial.
