### ISSUE TITLE
Update Lost Ark

### ISSUE THREAD

**Issue by bugproof** [Starz0r/AreWeAntiCheatYet#477]
### Game Title

Lost Ark

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

Apparently works with GeForce Now...

### Proof of Mention

https://www.nvidia.com/en-us/geforce/forums/gfn-game-requests/44/473967/lost-ark-on-geforce-now/3242656/

**Comment by AuthFailed** [comment]
Can we use Geforce Now on Linux? All the methods I've tried work through the web version, and have an extra input delay because of this method

**Comment by Curve** [comment]
> Can we use Geforce Now on Linux? All the methods I've tried work through the web version, and have an extra input delay because of this method

As far as I know only the web Versions work

**Comment by D3SOX** [comment]
> Can we use Geforce Now on Linux? All the methods I've tried work through the web version, and have an extra input delay because of this method

Try https://github.com/hmlendea/gfn-electron

**Comment by AuthFailed** [comment]
> > Can we use Geforce Now on Linux? All the methods I've tried work through the web version, and have an extra input delay because of this method
> 
> Try https://github.com/hmlendea/gfn-electron

It works exactly the same way as in the browser. Accordingly, it has the same problems, including long input delays.
Actually, there is another option that I could find. It's https://github.com/liberavia/geforcenow
There is a .appimage file option right there. However, even though it works for others, I couldn't get it to work and created an issue on github. The problem was with the installation, hanging up giving this error. Maybe this information will be useful to someone.
![image](https://user-images.githubusercontent.com/21986465/172060598-6235dfb7-4a5b-4ee8-b8ad-3811c83ee330.png)

**Comment by AuthFailed** [comment]
As I understand it, this version works through wine, and Geforce Now does not work through wine. Apparently, it used to work before some kind of innovations from NVIDIA

>
