### ISSUE TITLE
Fortnite added new Anti cheat

### ISSUE THREAD

**Issue by DevanPratt** [Starz0r/AreWeAntiCheatYet#560]
### Game Title

Fortnite

### Status of the Anti-Cheat

🚫 Denied

### Proof of Mention

https://fortnitetracker.com/article/1876/fortnite-adds-new-anti-cheat-in-effort-to-combat-rising-levels-of-foul-play#:~:text=In%20Wednesday's%20v21.20%20update,are%20currently%20unable%20to%20play.

**Comment by DevanPratt** [comment]
According to the anti cheat creator's [website](https://byfron.com), they support Linux but I doubt this will change Fortnite's status. Haven't been able to test to confirm though.

**Comment by Curve** [comment]
> According to the anti cheat creator's [website](https://byfron.com), they support Linux but I doubt this will change Fortnite's status. Haven't been able to test to confirm though.

Yeah probably, especially since Tim Sweeney explicitly doesn't want to support Linux.

And God damn three anticheats? That's absurd 

They should rather think about some proper match making system that matches likely cheaters against other likely cheaters instead of adding a dozen more client side anticheats lmao

**Comment by TheEssem** [comment]
> According to the anti cheat creator's [website](https://byfron.com), they support Linux but I doubt this will change Fortnite's status. Haven't been able to test to confirm though.

There's also [this tweet](https://twitter.com/0xNemi/status/1461512530682003457) by one of the founders which gives a little bit of hope regarding support for games on Wine/Proton in general. However, it seems like Hyperion in Fortnite in particular is an interesting case; it seems to run alongside EAC/BattlEye, instead of it being standalone like the others.

**Comment by Curve** [comment]
> > According to the anti cheat creator's [website](https://byfron.com), they support Linux but I doubt this will change Fortnite's status. Haven't been able to test to confirm though.
> 
> There's also [this tweet](https://twitter.com/0xNemi/status/1461512530682003457) by one of the founders which gives a little bit of hope regarding support for games on Wine/Proton in general. However, it seems like Hyperion in Fortnite in particular is an interesting case; it seems to run alongside EAC/BattlEye, instead of it being standalone like the others.

Yeah it makes sense to run the ac along side the others as from the website it seems the ac is way too weak for fortnites standards

**Comment by Etaash-mathamsetty** [comment]
> According to the anti cheat creator's [website](https://byfron.com), they support Linux but I doubt this will change Fortnite's status. Haven't been able to test to confirm though.

that particular anti cheat might support linux, but the actual problem is that fortnite actually detects wine now and stops you from playing with a popup saying "wine is not supported". (earlier you could actually load into the lobby, but you can no longer do that)
I guess this was a way to combat cheaters...?
